"""empty message

Revision ID: 4a9181e0b2a5
Revises: 7f88481c77aa
Create Date: 2023-04-01 20:18:34.637106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9181e0b2a5'
down_revision = '7f88481c77aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('bookId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('bookId',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
