"""empty message

Revision ID: 67ddd3ada910
Revises: bfb119b488f4
Create Date: 2023-03-31 21:15:28.559474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ddd3ada910'
down_revision = 'bfb119b488f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.String(length=40), nullable=True))
        batch_op.alter_column('bookName',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('bookName',
               existing_type=sa.String(length=40),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('userName')

    # ### end Alembic commands ###
