"""empty message

Revision ID: bfb119b488f4
Revises: a3cce0649cbb
Create Date: 2023-03-31 21:11:02.785818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb119b488f4'
down_revision = 'a3cce0649cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookName', sa.Integer(), nullable=True))
        batch_op.drop_column('review')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('bookName')

    # ### end Alembic commands ###
